Dev ems mikhail
gscwd-ictd/apps pull request #325
Opened 2023-06-07 08:44 UTC by leekimah

Added Schedule Sheets, removed office.

2023-06-07 08:50 UTC, dev-gscwd requested changes
Please check custom-group-store

2023-06-08 00:10 UTC, allyncubero approved these changes

2023-06-08 00:11 UTC, allyncubero approved these changes

2023-06-08 00:11 UTC, allyncubero approved these changes

2023-06-08 00:12 UTC, dev-gscwd approved these changes

2023-06-08 00:12 UTC, merged